housing$`Listing Office - Office Name` = NULL
housing$`List Agent - Agent Name` = NULL
housing$Status = NULL
housing$County = NULL
housing$DOM = NULL
housing$`Assessment Amount` = NULL
housing$`Assessment Year` = NULL
housing$`Price - List` = NULL
housing$`Price - Closed` = NULL
housing$`Price - Original` = NULL
housing$PicCount = NULL
housing$`Tax - Gross Amount` = NULL
housing$Surveyed = NULL
housing$`Showing Service`= NULL
housing$Seasonal = NULL
housing$`Short Sale` = NULL
housing$Rented = NULL
housing$`Foreclosed/Bank-Owned/REO`= NULL
housing$Easements = NULL
housing$`Current Use` = NULL
housing$Covenants = NULL
housing$`Basement Access Type` = NULL
housing$`Development / Subdivision` = NULL
housing$`MLS #`= NULL
housing$`Common Land Acres`= NULL