names(housing)[names(housing)=="Water Body Type"] <- "WBT"
names(housing)[names(housing)=="Water Frontage Length"] <- "WFT"
names(housing)[names(housing)=="Date - MLS List"] <- "DateMLS"
names(housing)[names(housing)=="Date - Closed"] <- "DateCL"
names(housing)[names(housing)=="Baths - Total"] <- "Baths"
names(housing)[names(housing)=="Bedrooms - Total"] <- "Bedrooms"
names(housing)[names(housing)=="Year Built"] <- "Built"
names(housing)[names(housing)=="Rooms - Total"] <- "Rooms"
names(housing)[names(housing)=="Garage Capacity"] <- "GarCap"
names(housing)[names(housing)=="Garage Type"] <- "GarType"
names(housing)[names(housing)=="Flood Zone"] <- "Flood"
names(housing)[names(housing)=="Total Stories"] <- "Stories"
names(housing)[names(housing)=="Property Type"] <- "PropType"
names(housing)[names(housing)=="Lot - Acres"] <- "LotAcr"